### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by timlee0119** [cmu-db/noisepage-control#7]
#### Short-term

- [ ] Publish stop_exploratory_postgres as completed in stop_exploratory_postgres.py
- [ ] Probe available port in /launch_exploratory_postgres instead of hard-coding to 20000 to allow multiple exploratory PG cluster to be launched
- [ ] Allow multiple primary / exploratory worker ports instead of hard-coding to 8001 / 8002 to allow concurrent tuning requests
- [x] Rename events to commands
- [ ] Benchbase execution
- [ ] Use importlib + getattr to make plugging in new data_collector easier

#### Long-term
- [ ] Spawn 3 workers on different machines
- [ ] Allow access via django models

### Codebase Enhancement
- [ ] Add automatic test cases
- [ ] Add Postman collection
- [ ] Add a configure script (set up postgres bin paths etc.)
- [ ] Add setup script (run rmq, production cluster etc.)
